### ISSUE TITLE
I don't seem to have this file

### ISSUE THREAD

**Issue by cnscdh** [World-of-Cryptopups/useAtomicAssets#1]
6598 error path E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0.1.tgz
6599 error errno -4058
6600 error enoent ENOENT: no such file or directory, open 'E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0.1.tgz'

**Comment by tbdsux** [comment]
> 6598 error path E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0.1.tgz 6599 error errno -4058 6600 error enoent ENOENT: no such file or directory, open 'E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0.1.tgz'

Sorry, since I haven't published it yet, I have been manually installing it first. You can follow bellow if you want to test the example.

You to pack it first and install it to the example. 
```
npm pack
```

Then install from the example folder.
```
npm install ../cryptopuppie-useatomicassets-0.0.1.tgz
```

**Comment by cnscdh** [comment]
> > 6598 错误路径 E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0.1.tgz 6599 错误 errno -4058 6600 错误 enoent ENOENT：没有这样的文件或目录，打开 'E:\useAtomicAssets-main\cryptopuppie-useatomicassets-0.0。 1.tgz'
> 
> 抱歉，由于我还没有发布它，我一直在手动安装它。如果你想测试这个例子，你可以按照下面的操作。
> 
> 您先将其打包并将其安装到示例中。
> 
> ```
> npm pack
> ```
> 
> 然后从示例文件夹安装。
> 
> ```
> npm install ../cryptopuppie-useatomicassets-0.0.1.tgz
> ```

ok  I'll try

**Comment by cnscdh** [comment]
When I try to run NPM start


Failed to compile.
./src/App.tsx
Module not found: Can't resolve '@cryptopuppie/useatomicassets' in 'E:\useAtomicAssets\example\src'

**Comment by cnscdh** [comment]
{
  "name": "example",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@cryptopuppie/useatomicassets": "file:./example-0.1.0.tgz",

**Comment by tbdsux** [comment]
> When I try to run NPM start
> 
> Failed to compile. ./src/App.tsx Module not found: Can't resolve '@cryptopuppie/useatomicassets' in 'E:\useAtomicAssets\example\src'

You need to run the `npm pack` on the root folder not on `example`. Then, you can install it with `npm install ../cryptopuppie-useatomicassets-0.0.1.tgz`.

**Comment by tbdsux** [comment]
I have published this library. You can now try to install it.
```sh
npm install @cryptopuppie/useatomicassets --save
```

**Comment by cnscdh** [comment]
thank you！



发自我的iPhone


------------------ Original ------------------
From: TheBoringDude ***@***.***&gt;
Date: Mon,Jan 24,2022 10:15 PM
To: World-of-Cryptopups/useAtomicAssets ***@***.***&gt;
Cc: cnscdh ***@***.***&gt;, Author ***@***.***&gt;
Subject: Re: [World-of-Cryptopups/useAtomicAssets] I don't seem to have thisfile (Issue #1)





 
I have published this library. You can now try to install it.
 npm install @cryptopuppie/useatomicassets --save
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
